
services:
  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=lambda,s3,iam,logs
      - DEBUG=1
      - AWS_DEFAULT_REGION=us-east-1
      - EXTRA_CORS_ALLOWED_ORIGINS=*
      - EXTRA_CORS_ALLOWED_HEADERS=*
      - EXTRA_CORS_EXPOSE_HEADERS=*
      - DISABLE_CORS_CHECKS=1
      - DISABLE_CUSTOM_CORS_S3=1
    volumes:
      - "./localstack/init:/etc/localstack/init"
      - "./localstack/lambda:/opt/lambda"
      - "./web:/web"
      - "/var/run/docker.sock:/var/run/docker.sock"

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - "./web:/usr/share/nginx/html:ro"
    depends_on:
      - localstack
